
export default {
  APP_NAME: 'Good Driver',
  DRIVE_SCORE: 'Drive\nand Score',
  DRIVE_SCORE_DESC: 'Become self aware, score better and become a better driver',
  SAFE_SECURE: 'Safe\nand Secure',
  SAFE_SECURE_DESC: 'Your driving score is average. Better score can help you get the.',
  WEEKLY_INCETIVE: 'Weekly\nIncentives',
  WEEKLY_INCETIVE_DESC: 'Weekly £50 Amazon voucher if you’re in the top 10 percentile draw.',
  SAVE_INSURANCE: 'Save\non Insurance',
  SAVE_INSURANCE_DESC: 'Data is safely secured and we do not share your data with any 3rd party without your permission.',
  SKIP: 'Skip',
  NEXT: 'Next',
  CONTINUE: 'Continue',
  I_AGREE: 'I Agree',
  get_started: 'Get Started',
  ENTER_MOBILE: 'Enter your\nmobile number',
  ENTER_MOBILE_DESC: 'We will send an sms with a verification code to this number',

  ENTER_CODE: 'Enter code\nsend to your phone',
  ENTER_CODE_DESC: 'We have sent an OTP to',
  HELLO_THERE: 'Hello there!',
  HELLO_THERE_DESC: 'Welcome to GoodDriver. Below you can see our Terms and Conditions as well as our Privacy Policy.\n\nPlease take out the time to review thses!',
  WHAT_EMAIL: 'What is\nyour email id?',
  WHAT_EMAIL_DESC: 'We need your email id',
  CHOOSE_COUNTRY: 'Choose Country',
  EMAIL_ID: 'Email id',
  WHAT_CAR: 'What is\nyour car registration?',
  WHAT_CAR_DESC: 'We need your car details to start adding trips.',
  EMAIL_ID: 'Email id',
  ENTER_NUMBER: 'Enter Number',
  INDIA: 'India',
  UK: 'UK',
  INDIA_CODE: '+91',
  UK_CODE: '+44',
  emphtyPhone: 'Please enter your phone number',
  errorEmail: 'Please enter your valid email id',
  errorCar: 'Please enter your car number',
  OTP_ERROR: 'Enter your OTP',
  TNC: 'Terms and conditions',
  PRIVACY_POLICY: 'Privacy Policy',
  PP_CONTENT: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.',
  TNC_CONTENT: 'To popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.',
  CAR_NUMBER: 'Car number',
  ALLOW_ALL_TIME: 'Allow all the time',
  ALLOW_ONLY: 'Allow only using the app',
  ASK_EVERY_TIME: 'Ask every time',
  WE_CANT_RECORD: 'We cant record your drives',
  WE_CANT_RECORD_DESC: 'For distraction- free. we need to be able to record your drives, when the app is closed.Dri=ve Settings > permissions > Locations and set to “ allow all the time “',
  ACTIVITY_TRACK: 'Activity Tracking',
  ACTIVITY_TRACK_DESC: 'Please enable activity Tracking, so we can track your drives.',
  GOTO_SETTING: 'Go to settings',
  ALLOW: 'Allow',
  DENY: 'Deny',
  ACTIVITY_TRACK_PERMISSION_MSG: 'Allow Telematics App to access your physical activity?',
  RUN_IN_BACKGROUND: 'Run in the Background',
  RUN_IN_BACKGROUND_DESC: 'To record your trips accurately, Telematics need to be able to run in the background.',
  CANNT_RECORD_DRIVES: 'We can’t record your drives. Kindly\nupdate your phone settings and enable\nthe permissions.',
  PERMISSION: 'PERMISSIONS',
  BUILD_ACCURATE_SCORE: 'To build an accurate score, Telematics needs\nto be able to record your drives. The options\nbelow are the key settings pending that allow\nTelematics to do this.',
  LOCATION_SERVICE: 'Location Services',
  ACITVITY_SERVICE: 'Activity Services',
  PENDING: 'Pending',
  COMPLETE: 'Complete',
  MILES:'Miles',
  NO_RUSH:'No Rush',
  WAITING_FOR_YOU_TO_TAKE:'We are waiting for you to take the drives to start calculating your scores. The score starts appearing once you complete 50 miles.',
  YOUR_TRIP_AUTOMATICALLY:'Your trips are automatically recorded in the background!',
  ACCELEration:'Acceleration',
  BREAKING:'Breaking',
  SPEEDING:'Speeding',
  SMOOTHNES:'Smoothness',
  DAY:'Day',
  NIGHT:'Night',
  PHONE_DISTRACTION:'PHONE DISTRACTION',
  MILES_DRIVEN:'Miles Driven',
  TOTAL_FAULTS:'Total Faults',
  TRIPS:'Trips',
  USER_PREF_KEY:'user_detail',
  SCREEN_NAME:'screen name at user present',
  VEHICLE_DETAIL_PREF_KRY:'vehicle pref key',
  RESEND_CODE:'Resend code',
  NOTIFICATIONS:'Notifications',
  YES:'Yes',
  NO:'No',
  ENTER_YOUR_ANSWER:'Enter your answer here',
  PLEASE_ANS:'Please fill your answer',
  SUBMIT:'Submit',
  ANSWER_SUBMIT_SUCCESS:'Survey submitted successfully.',
  QUOTE:'Quote',
  TRIPS:'Trips',
  ACTIVITY_PERMISSION:'Activity permission pref',
  SPEED_SPLIT:'SPEED LIMIT SPLITS',
  TAKE_SURVEY:'TAKE SURVEY',
  ARE_YOU_SURE_LOGOUT:'Are you sure want to logout',
  GPS_DISABLE : 'Please enable your GPS',
}